baseURL: https://fuckstealingart.com
languageCode: en-us
title: Fuck Stealing Art

theme: relearn

editURL: https://github.com/Allar/fuckstealingart/
author: Michael Allar
description: A resource to help combat the modern era of art theft across NFT platforms.
disableSearch: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  twitter:
    creator: "@michaelallar"
    site: "@michaelallar"
  disableShortcutsTitle: true

menu:
  shortcuts:
    - name: "<i class='fab fa-fw fa-github'></i> View on GitHub"
      identifier: gh
      url: "https://github.com/Allar/fuckstealingart"
      weight: 10

      